### ISSUE TITLE
Allow nested dependencies

### ISSUE THREAD

**Issue by AgentFire** [Fody/PropertyChanged#179]
I am very excited with this software and am already spreading the word, however, I would like to have support for nested properties when specifying `DependsOn` and `AlsoNotifyFor` attributes, like this:

```
public Card SelectedCard { get; set; }

[DependsOn("SelectedCard.Name")]
public string SomeProperty { get; set; }
```

Here, when `SelectedCard`'s name property gets changed, it will also change `SomeProperty` property. Note that type `Card` already has its `ImplementPropertyChanged` attribute defined.

The above must work vise versa if `AlsoNotifyFor` attribute is used instead.

**Comment by SimonCropp** [comment]
i think this is outside the scope of what this project is trying to achieve. and as an aside it is also really difficult to achieve

**Comment by SimonCropp** [comment]
i suggest you instead flatten your binding model. it will simplify all your code

**Comment by AgentFire** [comment]
Flattening all my view models into one would result in an explode. I still think this feature would be EXTREMEY useful.

**Comment by SimonCropp** [comment]
> this feature would be EXTREMEY useful.

agreed. but i dont see a way to implement it in a predictable manner. have u done a spike to see how complex it would be?

**Comment by AgentFire** [comment]
Well, assuming that the target type will have the `[ImplementPropertyChanged]` attribute, I dont see why that would be hard. And no, I haven't, not as yet. But I will look into the source soon.

**Comment by Shiloovr** [comment]
Hi, I just joined the request of David and I am certain that many encountered this need.
I think you did an amazing job. I use your library in any of my projects.
As David pointed out is really very necessary! This addition will make the perfect solution!
Today, I had to use the binding mechanism to implement the solution. But this is not an elegant solution because it allows only working with objects FrameworkElement.
I do not speak English. I used Google translation. Hope is understandable.

**Comment by undergroundwires** [comment]
Thumbs up for this request.

**Comment by distantcam** [comment]
Can someone write out the example code they expect when using this new feature? I'm having trouble understanding how you would like the finished code to look like.

**Comment by Shiloovr** [comment]
Hi Distantcam

Below is a link to the project, demonstrates the problem and the solution ...

https://drive.google.com/file/d/0B0C_KheExAN7X2pSTWMzcl9Jemc/view?usp=sharing

The solution is based on the binding mechanism.

This is not an elegant solution. This Work around. But it works.

It has two major problems:

1. It uses later scenes in DependencyObject. What makes a performance problem a very large number of binding.

2. Because the solution is based on a DependencyObject, then required to run on the UI thread.

Some explanation about the project:

On the left side of the window shows a list of servers. You can select for each server, whether it is in a state Online.

On the right there are two boxes to choose which servers: source and destination.

After selecting two servers, you can press the button Communicate to connect them.

In order button will be available, choose 2 servers online mode.

You can change the selections of servers, or alternatively change the status online and see how it affects the availability button.

Shilo

**Comment by Shiloovr** [comment]
Hi Distantcam,
Further to previous comments. A detailed answer to your request.

I would expect a solution based on tracking the object through the mechanism of PropertyChanged Instead of binding mechanism for the reasons stated above.

**Instead this code:**
![image](https://cloud.githubusercontent.com/assets/10143678/17319536/f8c1c9fe-5896-11e6-8a77-978b44a26ef3.png)


**I want to use this code:**
![image](https://cloud.githubusercontent.com/assets/10143678/17319566/1e7b582c-5897-11e6-8b0b-cef85406d8d3.png)

**Comment by Shiloovr** [comment]
Here's a simple case, very useful:
object in ViewModel layer , refers to the object in Model layer.
For example :

![image](https://cloud.githubusercontent.com/assets/10143678/17650114/7f6756f8-624d-11e6-83f9-3b1565097268.png)

**Comment by AgentFire** [comment]
Yes, yes, that's what I wanted. So now we wait for a fody member to respond <3

**Comment by jeremyVignelles** [comment]
It would be great if the dependency is detected automatically, without having to set an attribute.

The above sample code would:
1. Register and Unregister appropriately to `PropertyChanged` events each time the `User` property is modified.
2. When `User` is modified, raise a `PropertyChanged` event for `FullName`
3. When either the `FirstName` or `LastName` property is raised, handle it in `UserVM` and raise a `PropertyChanged` for `FullName`

However, this requires that the `User` property is managed by `PropertyChanged.Fody`, and that the properties you are depending on raises `PropertyChanged` when modified.

Also, I wonder if that would be possible to work with `ObservableCollection`s to work like a computed observable field, like so:

```C#
public class ShoppingCart {
   public ObservableCollection<Article> Articles { get; set; }
   public string TotalPrice => Articles.Sum(a => a.Price);
}
```

Of course, the sum is recomputed on each Add/Remove/Change operation

I don't know if this is even possible, but that would be awesome!

**Comment by Shiloovr** [comment]
Attached is a simple code that presents a solution to the problem. But without collections.
[https://drive.google.com/file/d/0B0C_KheExAN7aFVxSFhhVl85X28/view?usp=sharing](url)

In one of my previous comments, I published code that solves a complex problem, but for those who are feeling too lazy to check it, I've included additional code and simple.

The solution is based on the Binding Mechanism of ViewModel level. This is not an ideal solution, but it works.

Of course, in this case, would have been better to use the Binding In XAML level. But the purpose was to demonstrate the ability to use the Binding In ViewModel level.

Waiting for the staff of Fody help us solve the problem. Please !!

**Comment by jtheisen** [comment]
I have [just released Moldinium](https://github.com/jtheisen/moldinium) which does dependency tracking [the way Knockout does it](http://knockoutjs.com/documentation/computed-dependency-tracking.html).

I found out about Fody and PropertyChanged.Fody just today and I wonder if I like it's style of code generation better. I use Castle.Core to do something similar at runtime, so you need to type a bit more:

    public abstract class Course : IModel
    {
        public abstract String Name { get; set; }

        public abstract Room Location { get; set; }

        public virtual String Description
            => $"course {Name} in room {Location.Name}";
    }

    public abstract class Room : IModel
    {
        public abstract String Name { get; set; }
    }

Here, `Description` gets updated on changes to `Location.Name` too without any need for the programmer to point out the dependency.

Dependency tracking works without any type of code analysis, it's entirely a library thing. Code generation is only used for syntactic sugar, just like PropertyChanged.Fody.

Now that I know about Fody, there may be a reason to use it for my library too, and that apart from the potentially better syntax: I learned only a couple of days ago that runtime code generation isn't available on Xamarin iOS, which I think is kind of a bummer.

In any case, if anyone wants to try Moldinium, I will always support my current syntax even if I may support PropertyChanged.Fody's syntax in the future too (which would then make Moldinium a Fody Add-In).

While it may also make sense to put something like Moldinium's dependency tracking into PropertyChanged.Fody directly, there are things I plan for Moldinium that are likely overkill for anything simply named "PropertyChanged". (I was really coming from ideas about filtered and ordered collections that are efficiently refreshed from changes to underlying data, which is a whole new box of features that fit well into that problem domain. That part's not nearly release-ready though. And then there's lots of stuff that I want to do to the core dependency tracking regarding user friendliness, debugging tools and safety.)

Anyway, I would really enjoy some feedback on my new library, so that's why I put this ad here.

**Comment by Shiloovr** [comment]
Hi friends, there is something new? At least in future planning?

Jtheisen, I tried to work with your solution. Is a very nice solution, but it still contains some bugs ..

**Comment by jtheisen** [comment]
@Shiloovr If you file something more concrete, I'm happy to fix everything. So far, I didn't get much feedback.

**Comment by Moulde** [comment]
I just ran into this issue. It exactly matches the example that @Shiloovr posted.
https://github.com/Fody/PropertyChanged/issues/179#issuecomment-239679848

**Comment by tom-englert** [comment]
Another approach is the "ReleayEvents" feature of https://github.com/tom-englert/TomsToolbox/blob/master/TomsToolbox.Desktop/ObservableObject.cs, http://tomstoolbox.azurewebsites.net/html/69BB070F.htm, https://www.nuget.org/packages/TomsToolbox.Desktop/

It's (currently) limited to 1:1 property relations, and usage is not a elegant as it could be if integrated in Fody.PropertyChanged, as you have to declare relations via attributes, however it nicely cooperates with Fody.PropertyChanged and would solve the above problem:

```
namespace UnitTestProject1
{
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    using PropertyChanged;

    using TomsToolbox.Desktop;

    [TestClass]
    public class UnitTest1
    {
        [ImplementPropertyChanged]
        class UserEntity : ObservableObject
        {
            public string FirstName { get; set; }

            public string LastName { get; set; }

            public string FullName => string.Join(" ", FirstName, LastName);
        }

        [ImplementPropertyChanged]
        class UserVM : ObservableObject
        {
            public UserEntity User { get; set; }

            private void OnUserChanged()
            {
                RelayEventsOf(User);
            }

            [RelayedEvent(typeof(UserEntity))]
            public string FullName => User.FullName;
        }

        [TestMethod]
        public void TestMethod1()
        {
            var target = new UserVM();

            string fullName = null;

            target.PropertyChanged += (sender, e) =>
            {
                if (e.PropertyName == nameof(UserVM.FullName))
                    fullName = target.FullName;
            };

            Assert.AreEqual(null, fullName);

            target.User = new UserEntity();

            Assert.AreEqual(" ", fullName);

            target.User.FirstName = "tom";

            Assert.AreEqual("tom ", fullName);

            target.User.LastName = "englert";

            Assert.AreEqual("tom englert", fullName);
        }
    }
}
```

**Comment by SimonCropp** [comment]
sorry nested change tracking is beyond the cope of this project.

**Comment by jtheisen** [comment]
As I already said: If there's interest, I could contribute a "Fody.Moldinium" that gives nested change tracking  with the usage of Fody.PropertyChanged - and my regular [Moldinium](https://github.com/jtheisen/moldinium) can already be used, although with a different usage.

**Comment by aesalazar** [comment]
@jtheisen I would certainly be interested.

**Comment by Shiloovr** [comment]
@jtheisen I tried to work with your solution.
Your solution is good but it changes the syntax.
In addition, the use of abstract department is uncomfortable.
If you can make an effort and adapt it to the existing syntax, lots of programmers will thank you ...
For example, just code below

![image](https://cloud.githubusercontent.com/assets/10143678/26525460/5dbfad8a-4360-11e7-9d5b-af9e4c4dda67.png)

**Comment by jtheisen** [comment]
@Shiloovr Thanks for the feedback. Combining Fody with Moldinium would give the same syntax as Fody.PropertyChanged (perhaps slightly different attributes, but with an migration path). So I'll consider doing that then.

**Comment by Shiloovr** [comment]
Friends, I want to inform you that there is a solution that provides a response to nested objects as well.
The solution is very similar to Fody in that it is based on a class attribute.
The problem where they do not support the On_PropertyName_Changed method.
[https://github.com/postsharp/PostSharp.Samples/blob/master/PostSharp.Samples.Xaml/CustomerViewModel.cs](url)

**Comment by weitzhandler** [comment]
@Shiloovr link's broken

**Comment by Shiloovr** [comment]
@weitzhandler  Here is an updated link
[https://github.com/postsharp/PostSharp.Samples/blob/master/Xaml/PostSharp.Samples.Xaml/CustomerViewModel.cs](url)

**Comment by weitzhandler** [comment]
@Shiloovr Does this link work on your computer?
Could it be a private repo?
Because I get a 404.

**Comment by Shiloovr** [comment]
@weitzhandler 
Now I notice the problem. A little strange, but if you click the link directly, you will get a 404 error. But if you copy the address and paste it into the browser address bar, you will be able to surf.
I do not know why it is, just try.

**Comment by weitzhandler** [comment]
That's funny...
Maybe you should use a GitHub reference link.
Anyway thank you.

**Comment by SagarPanwala** [comment]
@Shiloovr  I know this is very old, but I'm still struggling with this functionality. I don't understand how the above link resolved the issue for you?

**Comment by weitzhandler** [comment]
Lol I don't think it did, I guess I was trying to find out what you did in attempt to resolve this. Been a while, don't really remember TBH.

**Comment by buzzware** [comment]
Xamarin => MVVM => PropertyChanged.Fody => this issue
