### ISSUE TITLE
Parameter for disable INotifyPropertyChanged

### ISSUE THREAD

**Issue by michalkress** [Fody/PropertyChanged#183]
Sometime I need disable Fody on one class. Now I must use attribute `[DoNotNotify]`, but is not good resolved, because I must use Fody attribute for disable it in this class.

My idea. For Fody add option parameter implement fody in every `INotyfyPropertyChanged` class. 

When I need use Fody for INotyfyPropertyChanged, I use
`[PropertyChanged.ImplementPropertyChanged]`
`class Person: INotyfyPropertyChanged`
`{...}`

**Comment by jeremyVignelles** [comment]
Hi,
I have the same issue here :
I have a project where I want to migrate the ViewModels that currently have manually-implemented "PropertyChanged" events to PropertyChanged.Fody.
My new ViewModels have `[ImplementPropertyChanged]`, but I don't want PropertyChanged.Fody to magically touch the legacy code and trigger PropertyChanged where it is not already (that could potentially reveal tons of new bugs ...).

Is there an option to tell PropertyChanged.Fody to touch only the classes that have the attribute?

**Comment by BarfieldMV** [comment]
It would be really handy if the ImplementPropertyChanged would be opt in even for classes implementing INotifyPropertyChanged.

**Comment by JimbobTheSailor** [comment]
I'd like to add some weight to the argument that only classes decorated with [ImplementPropertyChanged] should 'implement property changed.  (This is a similar thread to https://github.com/Fody/PropertyChanged/issues/116 but I paste here because this is the latest)

It is an unexpected behavior of Fody that a class that is not decorated with [ImplementPropertyChanged] will be 'weaved' if it is derived from INotifyPropertyChanged. What then is the purpose of the attributed [ImplementPropertyChanged] ? Why not delete it an rely on INotifyPropertyChanged? This would be less confusing, but would also be wrong. It is wrong because the current implementation of Fody *assumes* that the INofityPropertyChanged event should be fired for *every* property in the project (unless explicitly decorated with   [DoNotNotify])

Fody, in my view, should augment the normal programming model where a property does not throw the INPC event, unless the programmer wants it to.  Currently, the programmer does this within each property Set{} as you know. The beauty of Fody, is that I can now elect to do this at the class level, not at the property level, by including [ImplementPropertyChanged].  This is of terrific value for classes that are bound to XAML view, where I would normally implement the INPC for almost all, if not all, the properties in that class. Well, that is what I *thought* Fody does. But it doesn't, Fody makes me implement INPC for *every class* in my entire project. This fundamentally reverses the normal model of opting in to the INPC event, to explicitly opting out.  This is unexpected, and wrong. Most of my properties are interface properties to other objects, that have nothing to do with binding to a view. This just bloats the execution of the code by throwing a storm of unnecessary - and unexpected events. 

My strong preference is that I should retain control of when the INPC event is thrown at the property level, or at the class level, for that class only via the terrific [ImplementPropertyChanged]

**Comment by rotorgames** [comment]
@SimonCropp Hello. Why don't you add configuration for disabling `INPC` default behavior? You can add `[DoNotNotify]` for assembly or add property into Weavers xml. 

I think that `INPC` default behavior is bad because it has added unnecessary code in my xaml files. I use `Xamarin.Forms` and all `Views` in it use `INPC`. If I extend my class from any `Xamarin.Forms` `Views` class I will have two calls of `OnPropertyChanged`.

For example:

```csharp
public int TappedSelectorRadius
{
    get
    {
        return (int)this.GetValue(RgCircleSlider.TappedSelectorRadiusProperty);
    }
    set
    {
        if (object.Equals((object)this.TappedSelectorRadius, (object)value))
            return;
        this.SetValue(RgCircleSlider.TappedSelectorRadiusProperty, (object)value); // First call
        this.OnPropertyChanged("TappedSelectorRadius"); // Second call
    }
}
```

SetValue will invoke `OnPropertyChanged` and `OnPropertyChanged("TappedSelectorRadius")` will invoke it also. But I don't want it. 

I will have to add `[DoNotNotify]` in every class which extended from `Xamarin.Forms.View` and it is so bad. I have many classes which extended from Xamarin.Forms.View. 

Please, add configuration which disables `INPC` default behavior.

We will be very grateful.

**Comment by rotorgames** [comment]
P.S. You can prevent `INPC` behavior if you will use `FilterType` in your assemblies.

For example;

```chsparp
// INPC will be implemented only in Only.This.Namespace.* but will not be implemented in other namespaces
[assembly: FilterType(nameof(Only.This.Namesplace))] 

// If you want to add two or more namespaces you can do that:
[assembly: FilterType(nameof(Only.This.Namesplace)+"|"+nameof(Second.Namespace)+"|"+nameof(Third.Namespace))]  
```

**Comment by paul-kiar** [comment]
I do not think @rotorgames solution is a viable workaround.  This behavior is absolutely un-detectable as a programmer.  I ran across it because of a stack overflow being caused by a property on a class that didn't have the PropertyChanged.ImplementPropertyChanged attribute.  This behavior should be removed entirely, if you want Fody to do something with your class you should explicitly add the attribute.

**Comment by SimonCropp** [comment]
sorry i dont see the value in this proposal.

**Comment by ultimate-deej** [comment]
@SimonCropp This is a library. A developer wants to choose which parts of his codebase apply it to.

**Comment by JimbobTheSailor** [comment]
You don't see the value in it? That's all you have to say

Did you engage with the comments? Did you read and understand the magnitude
of the trouble this code causes? How many hours of work has my team lost
due to the unpredictable nature of this code as I outlined. Fody is a
virus, it alters code that you don't instruct it to alter. It causes
unpredictable and unexpected behaviour. Months ago I instructed our team to
re architect to get rid of fody. I was hoping that you would engage with
the concerns I raised. I suppose you provide it for free and so we have no
real influence. But , at current progress we will be fody free by October,
a good outcome

**Comment by ultimate-deej** [comment]
@JimbobTheSailor Strictly speaking it is not Fody itself, but this specific add-in. The fix must be trivial, and I believe your team could easily do a custom Fody.PropertyChanged version with the correct behavior.
Nevertheless, I agree that it must not alter code that you don't instruct it to alter.

**Comment by paul-kiar** [comment]
@SimonCropp If I create a PR with this behavior:
1.  When adding PropertyChanged to a project weaving only happens on classes that have [ImplementPropertyChanged]
2.  Existing projects both [ImplementPropertyChanged] and INotifyPropertyChanged classes get weaved.
3.  Existing projects can set a plugin parameter to turn off this behavior.
Will you consider it?

**Comment by SimonCropp** [comment]
Firstly let me apologize for the brevity of my response. I actively contribute to over 50 FOSS projects and just keeping my head above water requires a certain level of concise communication. Sometime is fall a little more on favoring my own private time over contributing my time for free to help other people. Even now i am responding to this at 11am on a saturday morning.

A project owner is free to say no to any feature simply on the grounds of the ROI is not worth it. The thing you need to remember that the effort involved in any feature is at least a factor of ten greater than the initial effort involved in the code. There is the cost of documentation, support, continual verification as the codebase evolved and fixing the inevitable bugs that will occur for any feature. All these costs are generally paid by the project maintainer over the span of several years after the initial feature was implemented. So forgive me for being weary of pushing back on phrasing like "please this is an easy feature". Saying yes is me saying i will dedicate my time for free for several years to keep it working.

At any point in time anyone is free to fork this project. I till even help via a code review and will publicize the project as a viable alternative on the readme of this project.

The `[ImplementPropertyChanged]` was never about opting in for property notification. This was called out in several locations clearly. The readme even contained the following in bold

> **NOTE: All classes that do not have `[ImplementPropertyChanged]` but still have `INotifyPropertyChanged` will have notification code injected into property sets.**

So the behaviour is

 1. all classes with `ImplementPropertyChanged` have INotifyPropertyChanged added
 2. All classes that implement `INotifyPropertyChanged` have property notifications injected

The aim of this project is

> Make the existence of INotifyPropertyChanged be the only thing need cause all property notty notifications to occur

With that in mind an opt in model does not make sense.

Regarding "what if i already have notifications for certain classes properties" this ideally should not be a problem since notifying for a property, when there is nothing attached, is harmless.

Regarding "what if i already have legacy codebase that i am scared of". In this scenario i would recommend adding a single attribute to each `[DoNotNotifyAttribute]` to each legacy class. In the scheme of things this is a very small amount of code. The new classes can omit the `[DoNotNotifyAttribute]` and you can optional+gradually remove `[DoNotNotifyAttribute]` from legacy classes

@ultimate-deej

> This is a library. A developer wants to choose which parts of his codebase apply it to.

And using the `[DoNotNotifyAttribute]` they can

@JimbobTheSailor 

> Fody is a virus, it alters code that you don't instruct it to alter. It causes unpredictable and unexpected behaviour. 

I am sorry it cause your project friction. but the "unpredictable and unexpected behaviour. " as you call it is documented in several locations and has always been the way the project operated. But i take you point, perhaps the ` [ImplementPropertyChanged]` is a misleading/flawed feature. Given it only really saves people one line of i have removed this feature in version 2 https://github.com/Fody/PropertyChanged/issues/242

> Months ago I instructed our team to re architect to get rid of fody

I fully agree with you that any tool/library that the cost in time/effort/debugging/friction is greater than the value it delivers then you should burn all usages of that tool/library.

@paul-kiar 

I dont mind reviewing any proposed PR, but TBH i still dont see the friction here over, as i said above, simply adding `[DoNotNotifyAttribute]` to each class you want to opt out from. so while i would review and consider i make no promises of merging it.

> This behavior is absolutely un-detectable as a programmer. I ran across it because of a stack overflow being caused by a property on a class that didn't have the PropertyChanged.ImplementPropertyChanged attribute. This behavior should be removed entirely, if you want Fody to do something with your class you should explicitly add the attribute

undetectable other than the fact that is is clearly documented in several places. but you are correct in that perhaps it is flawed API, so it is now removed https://github.com/Fody/PropertyChanged/issues/242

Does any one want to get on a VOIP call to discuss this further? happy to do a crazy time of night (since i am in Australia) if it makes things easier

**Comment by jjlucsy** [comment]
I have to admit, the removal of this attribute is troubling. I go from a single line attribute to adding an interface, a property, and either disabling warning CS0414 or adding in code to reference the property otherwise the compiler spits out warnings. I wonder if renaming the attribute to something more descriptive would have been more appropriate. Perhaps [AddPropertyChangedInterface] or something along those lines.

**Comment by SimonCropp** [comment]
> I wonder if renaming the attribute to something more descriptive would have been more appropriate. Perhaps [AddPropertyChangedInterface] or something along those lines.

I think no matter the attribute name it would be mis-interpreted as "oh look this is how i make the class for notification"

**Comment by jjlucsy** [comment]
Perhaps. And perhaps I'm just trying to get my favorite feature added back in.
 [AddPropertyChangedEventAndInterfaceToClass] I really don't care how descriptive the attribute is, since the name completion and/or text replacement is easy to use.

**Comment by SimonCropp** [comment]
@ultimate-deej @JimbobTheSailor @paul-kiar thoughts on the above?

**Comment by distantcam** [comment]
I've seen this so many times.

```
[ImplementPropertyChanged]
public class SomeViewModel : ViewModelBase
```

What about `[INotifyPropertyChanged]`?

**Comment by SimonCropp** [comment]
@distantcam to save one line of code? (the event declaration)

as for "I've seen this so many times." yeah i think we had a bug related to that since according to this it should not have been possible

https://github.com/Fody/PropertyChanged/blob/ba5d8650321dc88c91046e4301a9c4efc5da6fba/PropertyChanged.Fody/TypeNodeBuilder.cs#L62

**Comment by distantcam** [comment]
> to save one line of code? (the event declaration)

I guess? I never understood the need for the attribute to begin with.

**Comment by SimonCropp** [comment]
yeah i got talked into "it is a cool feature what harm can it cause"

**Comment by distantcam** [comment]
I bet it was easy to implement too.

It's easier to solve with a base class instead of adding an attribute
everywhere.

**Comment by SimonCropp** [comment]
i think it might have been @petersgiles who talked me into it??

**Comment by petersgiles** [comment]
@SimonCropp my entire purpose on this planet is to talk you into things you don't want to do :)

**Comment by ultimate-deej** [comment]
@SimonCropp You have a point.
What I think is that any library feature must be opt-in unless it is a framework. That's what I would expect from a library. And others probably too because that's how libraries usually work.
But as you stated the aim of this project is the opposite. So, you may need to say it out loud to make it clear to everyone: opt-in is not going to happen, make a fork, that's the only way to go!

**Comment by 0x53A** [comment]
There is already a way to move from opt-out to opt-in:

```C#
[assembly: PropertyChanged.FilterType("My.Specific.OptIn.Namespace.")]
```

I use this successfully in a legacy project to scope the rewriting to only one namespace.

**Comment by BrunoJuchli** [comment]
@SimonCropp  I don't know who else was involved in the "talking you into it" part, but I'm pretty sure I was involved ([implementing it](https://github.com/Fody/PropertyChanged/commit/e9245dd0bfe900d14c30119db8cacbf7392b3223#diff-5c2ca26da4d4c13143ed20c57b5a28df)). Sorry it has caused you trouble and lost time. Sorry I wasn't "here" to take this on me. I should have and I could have - just didn't notice it. I've added myself on the watchlist so that I hopefully should notice it in the future. If not, please ping me. Of course I cannot and don't want to "take the project from you" but at least I could discuss the problems with the issue-raisers (take some of the heat), make suggestions (for your decision) and implement them.

The initial reasonale on my part for this feature was simple data classes that needed property changed notification. And as stated by others before, there's the CS0067 warning which we don't want to disable because in other cases it actually is of benefit.

**Comment by BrunoJuchli** [comment]
@0x53A could you add this opt-in method to the [readme](https://github.com/Fody/PropertyChanged/edit/master/README.md)? Maybe as an extra bullet after "To prevent a specific class from having the notification call injection, use the DoNotNotify attribute."?

 If I had enough knowledge about this feature I would have done it myself. However, I could not find any reference to this feature, neither on this repo nor in the microsoft documentations. Thanks!

**Comment by 0x53A** [comment]
> nor in the microsoft documentations

That's because it is a Fody.PropertyChanged Attribute ;)

I added a note to the readme, but afaik the wiki can't be pull-requested.

https://github.com/Fody/PropertyChanged/pull/278

**Comment by BrunoJuchli** [comment]
@0x53A thanks. I should have searched for `FilterTypeAttribute`, not `FilterType`, in the repository... *smacking my head*

**Comment by 0x53A** [comment]
Yeah, I assume github indexes by full words, so you only find it if you search the exact string, not a substring.

**Comment by JimbobTheSailor** [comment]
Farewell Fody Property Changed. The last code was remove today. So many
[DoNotNotify] in so much legacy code. No tool ever should require the
altering of legacy code to implement. Only the classes that I decorate to
use PropertyChanged with [ImplementPropertyChanged] should use this tool.
It would have been so useful, but no, it was not an opt in model, it got
into everything.The [ImplementPropertyChanged]  had no meaning, and it was
implemented everywhere.  No other tool has every caused so much trouble. It
is staggering that the [ImplementPropertyChanged] has no purpose and
confuses the author that including it invokes the weaving. Such a deceptive
tool, like a virus, it gets into everything.

Final Nuget uninstall done tonight.

**Comment by distantcam** [comment]
Farewell @JimbobTheSailor, you will not be missed.

**Comment by JimbobTheSailor** [comment]
But I miss what Property Changed promised. I miss what it could have been.
I miss how convenient and useful a concept it was, I miss how much time it
could have saved me if implemented correctly, I miss the good intent of the
people who made it, I miss opportunity lost.

If only it weaved in only the classes that I decorate with
[ImplementPropertyChanged] and no other. We could have been great friends

**Comment by jjlucsy** [comment]
@JimbobTheSailor Do you realize the attribute was renamed to AddINotifyPropertyChangedInterface in recent releases? I didn't know he made that change either till I went to use the old name and saw the name at the top of my auto-completion list.
