### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'ContainsTypeChecker' threw an exception

### ISSUE THREAD

**Issue by jrummell** [Fody/PropertyChanged#20]
I'm getting the following build error in multiple projects after upgrading the PropertyChanged.Fody NuGet package to 1.36.2.3

C:\myproject\Fody.targets(51,5): error MSB4018: The "Fody.WeavingTask" task failed unexpectedly.
C:\myproject\Fody.targets(51,5): error MSB4018: System.TypeInitializationException: The type initializer for 'ContainsTypeChecker' threw an exception. ---> System.InvalidCastException: Unable to cast transparent proxy to type 'IContainsTypeChecker'.
C:\myproject\Fody.targets(51,5): error MSB4018:    at ContainsTypeChecker..cctor() in c:\Code\Fody\Fody\ContainsTypeChecker.cs:line 15
C:\myproject\Fody.targets(51,5): error MSB4018:    --- End of inner exception stack trace ---
C:\myproject\Fody.targets(51,5): error MSB4018:    at ContainsTypeChecker..ctor()
C:\myproject\Fody.targets(51,5): error MSB4018:    at Processor..ctor() in c:\Code\Fody\Fody\Processor.cs:line 29
C:\myproject\Fody.targets(51,5): error MSB4018:    at Fody.WeavingTask.Execute() in c:\Code\Fody\Fody\WeavingTask.cs:line 46
C:\myproject\Fody.targets(51,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
C:\myproject\Fody.targets(51,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask, Boolean& taskResult)

**Comment by abelbraaksma** [comment]
This error can also appear with other Fody-dependent packages. I had it [within the NCrunch test system and ModuleInit.Fody](http://forum.ncrunch.net/yaf_postst1292_Ncrunch-Fody-ContainsTypeChecker.aspx). The cause was that when installing or upgrading `ModuleInit.Fody`, it did not reliably choose the same Fody package, resulting in the MSBuild tasks in the csproj and fsproj files containing different versions of Fody in different projects.

The resolution was the same as posted here by jrummel: install/uninstall Fody separately from the dependent packages, that way you can make sure that the correct version is present. Install packages dependent on Fody only *after* you have already installed Fody itself.

Sometimes uninstalling Fody leaves the MSBuild tasks in the project. Simply search solution-wide for the version string and you should be able to find whether or not all your projects have been updated correctly.

**Comment by SimonCropp** [comment]
@abelbraaksma can u give me a sequence of nuget commands that reproduces this

**Comment by SimonCropp** [comment]
@abelbraaksma "Sometimes uninstalling Fody leaves the MSBuild tasks in the project." this is a nuget and should be raised with them
