### ISSUE TITLE
Bind to Observablecollection with INotifyPropertyChanged

### ISSUE THREAD

**Issue by brambossche** [Fody/PropertyChanged#211]
Hi, 

I have an observablecollection class of this type:
 `public class ObservableCollectionEx<T> : ObservableCollection<T> where T : INotifyPropertyChanged`

I'm using entity framework model to code which generates a partial class. I don't want to change this class as it is autogenerated.
As the class is partial I found the following to implelementation INotifyPropertyChanged: adding a file with the attribute on the partial class
```
    [ImplementPropertyChanged]
    public abstract partial class UserSettings ......
```

This works, but when I want to do this:
 `public static ObservableCollectionEx<SQLiteConnection.UserSettings> UserSettings;`

It tells me the class does not implement INotifyPropertyChanged

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0311	The type 'Soleras.LIB.SQLiteConnection.UserSettings' cannot be used as type parameter 'T' in the generic type or method 'ObservableCollectionEx<T>'. There is no implicit reference conversion from 'Soleras.LIB.SQLiteConnection.UserSettings' to 'System.ComponentModel.INotifyPropertyChanged'.	
> How can I solve this ? 

Regards

**Comment by distantcam** [comment]
The `ImplementPropertyChanged` attribute only adds the `INotifyPropertyChanged` interface _after_ compilation. Because `UserSettings` doesn't have `INotifyPropertyChanged` on it the compiler fails, and PropertyChanged never gets a chance to add `INotifyPropertyChanged`.

Unfortunately this means you cannot use `ImplementPropertyChanged` in your scenario. Instead just implement `INotifyPropertyChanged` on the `UserSettings` class, and PropertyChanged will fill in whatever is missing that it needs.

**Comment by brambossche** [comment]
Ok, perfect.
I implemented it like this and it works
Thanks

**Comment by SimonCropp** [comment]
closed since there is a workaround
