### ISSUE TITLE
PropertyChanged allocations

### ISSUE THREAD

**Issue by LadislavLang** [Fody/PropertyChanged#222]
Hi, 
according to readme, generated code contains "new PropertyChangedEventArgs(propertyName)" allocation every times, when OnPropertyChanged is called.
It can be easily fixed by preallocated static PropertyChangedEventArgs for each property. Something like this: 

```
    static PropertyChangedEventArgs familyNameEventArgs = new PropertyChangedEventArgs("FamilyName");
    string familyName;
    public string FamilyName
    {
        get { return familyName; }
        set 
        {
            if (value != familyName)
            {
                familyName = value;
                OnPropertyChanged("FamilyName");
            }
        }
    }

    public virtual void OnPropertyChanged(string propertyName)
    {
        var propertyChanged = PropertyChanged;
        if (propertyChanged != null)
        {
           propertyChanged(this, familyNameEventArgs);
        }
    }
```

**Comment by SimonCropp** [comment]
is this really a concern in a user interface app? how many propertyChanged events are you firing hat you can even measure it?

**Comment by LadislavLang** [comment]
Allocations leads to GC a GC slowdown application ... so it is good practice to avoid unnecessary allocations, especially in 3rd part libraries, where the code is not in users control.

In our case, there are ~3000 fired PropertyChanged events per second.

**Comment by SimonCropp** [comment]
Ok. Can u send a PR for this change

**Comment by LadislavLang** [comment]
Hi, I'm sorry, but I'm not familiar with github processes and don't know how to create PR :/

**Comment by SimonCropp** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by distantcam** [comment]
This is similar to #52. The change would be difficult because many MVVM frameworks only use a property name instead of a full `PropertyChangedEventArg`.

So lets test the theory that a static cached variable will dramatically reduce the memory profile.

https://gist.github.com/distantcam/8b055f3a9b6c704e6c103e170ee100ab

``` ini

BenchmarkDotNet=v0.10.5, OS=Windows 10.0.14393
Processor=Intel Core i7-7700K CPU 4.20GHz (Kaby Lake), ProcessorCount=8
Frequency=4101568 Hz, Resolution=243.8092 ns, Timer=UNKNOWN
  [Host]     : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1637.0
  DefaultJob : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1637.0


```
 | Method | ModelCount | ChangeCount |          Mean |         Error |        StdDev |      Gen 0 |    Allocated |
 |------- |----------- |------------ |--------------:|--------------:|--------------:|-----------:|-------------:|
 | **Normal** |         **10** |          **10** |      **13.74 us** |     **0.0633 us** |     **0.0495 us** |     **1.5462** |      **7.03 kB** |
 | Cached |         10 |          10 |      13.47 us |     0.1042 us |     0.0924 us |     1.2441 |      5.86 kB |
 | **Normal** |         **10** |         **100** |     **152.25 us** |     **3.0048 us** |     **2.8107 us** |    **15.3483** |     **73.83 kB** |
 | Cached |         10 |         100 |     142.32 us |     2.0159 us |     1.8857 us |    12.5977 |     62.11 kB |
 | **Normal** |         **10** |        **1000** |   **1,504.72 us** |     **8.1230 us** |     **7.2008 us** |   **169.1406** |    **776.97 kB** |
 | Cached |         10 |        1000 |   1,498.53 us |    29.0124 us |    28.4941 us |   142.9688 |     659.8 kB |
 | **Normal** |         **10** |        **5000** |   **8,325.17 us** |    **98.2550 us** |    **91.9078 us** |   **838.5417** |    **4058.4 kB** |
 | Cached |         10 |        5000 |   7,667.71 us |   105.5566 us |    98.7377 us |   728.1250 |   3472.52 kB |
 | **Normal** |        **100** |          **10** |     **140.52 us** |     **3.0644 us** |     **2.7165 us** |    **14.6810** |     **70.31 kB** |
 | Cached |        100 |          10 |     136.79 us |     2.6083 us |     2.5617 us |    11.6211 |      58.6 kB |
 | **Normal** |        **100** |         **100** |   **1,508.17 us** |     **5.6723 us** |     **4.4286 us** |   **160.4167** |     **738.3 kB** |
 | Cached |        100 |         100 |   1,410.33 us |    20.4525 us |    19.1313 us |   129.0365 |    621.11 kB |
 | **Normal** |        **100** |        **1000** |  **15,197.48 us** |   **106.9130 us** |    **94.7755 us** |  **1757.2917** |   **7769.81 kB** |
 | Cached |        100 |        1000 |  14,812.87 us |   144.9448 us |   128.4898 us |  1327.0833 |   6598.01 kB |
 | **Normal** |        **100** |        **5000** |  **78,518.92 us** |   **770.4015 us** |   **682.9408 us** |  **9391.6667** |  **40582.75 kB** |
 | Cached |        100 |        5000 |  77,426.59 us | 1,446.9746 us | 1,421.1224 us |  7937.5000 |  34723.74 kB |
 | **Normal** |       **1000** |          **10** |   **1,488.26 us** |    **29.1525 us** |    **40.8678 us** |   **150.8789** |    **703.14 kB** |
 | Cached |       1000 |          10 |   1,399.49 us |    24.0648 us |    22.5103 us |   123.8281 |    585.97 kB |
 | **Normal** |       **1000** |         **100** |  **15,261.32 us** |   **210.8189 us** |   **176.0433 us** |  **1621.8750** |   **7383.04 kB** |
 | Cached |       1000 |         100 |  14,205.83 us |   248.3671 us |   232.3227 us |  1361.4583 |   6211.15 kB |
 | **Normal** |       **1000** |        **1000** | **153,954.46 us** | **2,345.4935 us** | **2,193.9759 us** | **18370.8333** |  **77696.72 kB** |
 | Cached |       1000 |        1000 | 154,154.47 us | 1,854.4651 us | 1,734.6677 us | 15562.5000 |  65977.39 kB |
 | **Normal** |       **1000** |        **5000** | **800,258.21 us** | **5,554.6387 us** | **5,195.8120 us** | **98548.6111** | **405823.22 kB** |
 | Cached |       1000 |        5000 | 801,983.90 us | 4,239.4597 us | 3,965.5929 us | 84150.0000 | 347228.94 kB |

So the cached version does allocate less than the normal one, but not as much.

> In our case, there are ~3000 fired PropertyChanged events per second.

Wow! Are those properties bound to the UI? If so your problem won't be the allocations of `PropertyChangedEventArgs`, the problem will be the complete overloading of the rendering system. If those properties aren't bound to the UI, why do they need a propertychanged? Or are you using those events to trigger code within your system, how efficient is that code to be able to handle 3000 events a second?

**Comment by SimonCropp** [comment]
closing this one for now. if u ever get around to a PR, and it does not add un-due complexity, we can merge that
