### ISSUE TITLE
Support NetStandard

### ISSUE THREAD

**Issue by arontsang** [Fody/PropertyChanged#227]
It would be awesome if we supported .net Standard and .net Core

**Comment by SimonCropp** [comment]
will try to get to this this week

**Comment by graemechristie** [comment]
This would be greatly appreciated. Using NetCore.Portability workaround is not building for us in Vs2017.

**Comment by SimonCropp** [comment]
happy to accept a PR for this if you want it sooner than my timeline allows

**Comment by sebandraos** [comment]
Working on a PR now. Solved the first issue I had of null reference when mscorlib wasn't found (https://github.com/Fody/Fody/issues/280 and https://github.com/Fody/PropertyChanged/issues/205). That weaves. The (only) issue I am now facing is that of Attribute being defined in the wrong assembly (https://github.com/Fody/Fody/issues/298). This has me stymied because there is no version of .NetStandard compatible with .NetFramework 4.0. One option is therefore to multi-target the PropertyChanged project. This is the route I'm going to work down but if there is a better solution please let me know. I also have no idea how Pepita is configured or will deal with this.

**Comment by SimonCropp** [comment]
>  I also have no idea how Pepita is configured or will deal with this.

u can add files here https://github.com/Fody/PropertyChanged/blob/master/NuGet/Nuget.csproj#L36

> no version of .NetStandard compatible with .NetFramework 4.0.

i am happy to drop net 4 support

**Comment by sebandraos** [comment]
So if I convert PropertyChanged to .NetStandard1.0 we're happy?
Great, I'll tweak that in Nuget.csproj

**Comment by sebandraos** [comment]
PR https://github.com/Fody/PropertyChanged/pull/228

**Comment by danielkatz** [comment]
Is there any ETA on this?

**Comment by SimonCropp** [comment]
ETA for a beta is within 24 hours. 

BTW i am planning to support only netstandard1.4 and up https://docs.microsoft.com/en-us/dotnet/articles/standard/library  so this will be a breaking change version

**Comment by SimonCropp** [comment]
2.0.0-beta001 is on nuget

**Comment by ergo-lkuendig** [comment]
thank you very much for the great work simon!
