### ISSUE TITLE
Support for .NET Framework 4.0?

### ISSUE THREAD

**Issue by MarkLTX** [Fody/PropertyChanged#270]
I stumbled across this comment...
"version 2 has been moved to netstandard1.3 which means you need to update to at least .net 4.6."

I'm no sure what that means. 

Does it mean I can't target the 4.0 framework in my projects that use PropertyChanged.Fody?

Or does it just mean I need .net 4.6 on my build machine?

**Comment by tom-englert** [comment]
Currently you can't even use it with Net4.0.  
PR #273 can fix this.

**Comment by SimonCropp** [comment]
It supports 4.5 and up. I am not sure there is a compelling reason that it should support a framework released 7 years ago with support ending last year

**Comment by tom-englert** [comment]
In industry the reality is different - there is a lot of legacy code and hardware around. 
If you compile against 4.0 (because you e.g. don't need any of the new features), it will happily run on 4.7, but also still works on the old isolated controller hardware working for years without the need to update it.

Since there is nearly no effort to support both, why don't do it?

**Comment by MarkLTX** [comment]
I don't WANT to target 4.0.  I HAVE to target 4.0.  My company runs a billion dollar business with commercial software that is not compatible with later versions of .NET.  I have no power to change this.

Lack of support for 4.0 is killing me.  I can use the older nuget package for now but I'm extremely reluctant to use Fody for any new development at this time after getting the rug pulled out from under me.

**Comment by SimonCropp** [comment]
@MarkLTX how about this. point me to one significant contribution your billion dollar business has made to any open source project in the past month and i will go to the effort of supporting .net 4.0

**Comment by SimonCropp** [comment]
i guess my underlying problem with this scenario is: you have a problem "your company refuses to keep their software reasonably up to date", and your request for a free open source project to keep supporting you is, in effect, attempting to make your problem someone else problem. 

you need to be highlighting to your organisation that the longer you leave things ot updated the more friction that will cause in development for people trying to use newer tools.

based on your current argument, if any raises an issue with "my company refuses to move off ,net 2/3 or 4" then the community should support that no questions asked. 

There has to be some point at which there is diminishing returns combined with increasing effort to support, that a project should be able to say "i am sorry we cant support that"

**Comment by tom-englert** [comment]
@SimonCropp reality is much more complicated, it's not just "my company", it's also all customers in the world with their IT, support engineers and a lot more ...
Sometimes it's really makes your live easier to demand only Net4.0 just to avoid endless discussions and support calls upfront.
I hope my open source contributions are enough to qualify me for requesting that feature, since it only needs to merge PR #273 to fix it :smirk:

**Comment by dss539** [comment]
While @SimonCropp is certainly correct that no one should _demand_ something with an entitled attitude, @tom-englert has apparently provided the work to make it happen.

If there is no increased burden or downside for merging #273 then it would be best to accept it. Is there is some negative aspect to it, then by all mean reject it. Then @tom-englert would just have to fork PropertyChanged.Fody to provide that support if he's willing.

**Comment by tom-englert** [comment]
@SimonCropp just stepped over this issue again:
Even though our application is using .Net4.6, the WiX Bootstrapper of course **must** be .Net 4.0 client, since it's impossible to install .Net4.6 from within an application that already reqiures .Net4.6. 
Since we can't assume that .Net4.6 or newer is already installed on every machine, the bootstapper must be able to start on .Net4.0client and upgrade .Net if necessary.

So it would be great if you could accept my PR so we can keep our packages up to date.

**Comment by SimonCropp** [comment]
@tom-englert i really want to help here. But the long term ramifications of saying yes anytime someone asks to support an older runtime, are not maintainable for me moving forward. Take you wix example, someone could equally say "tool x only supports net 3, can u support that" and based on  the arguments above i would have to support it. 

Btw it looks like wix does have checks for net 462 https://stackoverflow.com/questions/39896281/  and if it doens u really should be pushing the wix team to add native support for supported version of net. If they have no plans to then itis probably abandonware and u should startplanning on how to remove that dependency. Also ether r significant bug fixes and per improvments in newer versions of net. Being stuck on an older versions due to a dodgy installer is something u need to find a solution to 

So again really sprry. But i am going to close this. I have also  clarified the supported versions here https://github.com/Fody/Fody#supported-runtimes

**Comment by arackaf** [comment]
Yo @MarkLTX - how much money is your billion dollar company willing to pay to the maintainers of this OSS project to support .net 4?
