### ISSUE TITLE
Extend DependsOnAttribute for commands

### ISSUE THREAD

**Issue by jlnostr** [Fody/PropertyChanged#281]
When using an `RelayCommand` (e.g. from MvvmLight), where the `CanExecute` depends on the value of a property, the `DependsOnAttribute` could be extended, so each time the property changes, the `RaiseCanExecuteChanged()` method of the command is invoked.

**Comment by SimonCropp** [comment]
Can u upload a repro that include before and after code to illustrate how u think it should work

**Comment by jlnostr** [comment]
Yep, did it. You can see the main code describing the problem [here](https://github.com/jlnostr/Fody-Command-PropertyChanged-Sample/blob/master/App2/Fody.cs).

**Comment by SimonCropp** [comment]
Sorry this is outside the scope of what this project is designed to own 

Perhaps a different weaver that runs after prop changed should be built? Perhaps similar to https://github.com/DamianReeves/Commander.Fody

**Comment by zihotki** [comment]
Hey, this issue is closed but anyway I'd like to share my 2 cents since I stumbled upon same issue multiple times and I feel like this is a good addition to the awesome library to have a way to invalidate command execution state.
All we need to do to support that (via attributes) is to put a call `CommandManager.InvalidateRequerySuggested()` after putting raising property notification. To detect that we need to inject that code a simple check can be made - check whether the property type implements ICommand interface. There is no need, IMO, to implement automatic dependency detection since it'll be too complex. Attributes are good enough.
Why it's better to implement it's here - this library already has all needed attributes and logic to determine dependencies. 
Let me know what you think, I can try to create a PR with draft implementation and we can discuss it.

**Comment by SimonCropp** [comment]
@zihotki having not done real wpf/xaml in several years i am prob not qualified to have an opinion on this. but does this come close to meeting your requirement https://github.com/DamianReeves/Commander.Fody ?

**Comment by zihotki** [comment]
Unfortunately it doesn't provide any value. While PropertyChanged helps to considerably reduce boilerplate code, the project you are referencing to helps only to define the commands. The same can be achieved by a line of code using any MVVM framework. 
This is the code using Commander.Fody:
```
public class SurveyViewModel
{
    [OnCommandCanExecute("SubmitCommand")]
    public bool CanSubmit()
    {
        ... 
    }
    [OnCommand("SubmitCommand")]
    public void OnSubmit(){
        ...
    }        
}
```
And this is the same code using MvvmLight:
```
public class SurveyViewModel
{
    public RelayCommand SubmitCommand { get; } = new RelayCommand(OnSubmit, CanSubmit);
    public bool CanSubmit()
    {
        ... 
    }
    public void OnSubmit(){
        ...
    }        
}
```
And the former doesn't work with IntelliSense well. IMO that project is completely useless, or at least I just don't see any value.
But initial suggestion was to help to implement the auto-triggering refresh of a command state, not about implementing commands. Auto-triggering refresh of a command state more belongs to this project since it implements the INPC boilerplate code and it has enough capabilities and knowledge to do that as well. And all it needs is to detect properties with types implementing `ICommand` (by the way, it may be a good idea to add a setting to ignore them for INPC injection since commands usually never get changed), get dependency properties, put them in hashset and in NPC method add a condition to check the property name in the hashset and call one static method without any parameters.

**Comment by tom-englert** [comment]
Raising a property change event on the command property itself should have the same effect as triggering the `CommandManager.InvalidateRequerySuggested() `, so that should work already:

```C#
public class SurveyViewModel
{
    public bool IsSubmitEnabled { get; set; }

    [DependsOn(nameof(IsSubmitEnabled))]
    public RelayCommand SubmitCommand { get; } = new RelayCommand(OnSubmit, CanSubmit);

    public bool CanSubmit()
    {
        return IsSubmitEnabled;
    }
    public void OnSubmit(){
        ...
    }        
}
```

**Comment by zihotki** [comment]
@tom-englert Good point, somehow I didn't think about it. Tested and verified that it indeed works like a charm.
