### ISSUE TITLE
Could not inject EventInvoker method on type

### ISSUE THREAD

**Issue by tzachshabtay** [Fody/PropertyChanged#316]
Fody.PropertyChanged version: 2.2.5

My solution compiles fine from both visual studio and visual studio for mac.
It fails to compile, however, from Travis CI or from Appveyor CI.

The error message: 

> MSBUILD : error : Fody: Could not inject EventInvoker method on type 'AGS.Engine.AGSButton'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Either correct 'EventInvokerNames' or implement your own EventInvoker on this class. If you want to suppress this place a [DoNotNotifyAttribute] on AGS.Engine.AGSButton. [C:\projects\monoags\Source\Engine\AGS.Engine\AGS.Engine.csproj]

Complete log: https://ci.appveyor.com/project/tzachshabtay/monoags/build/1.0.522/job/v42a3fyq5djabjyf

My solution is here: https://github.com/tzachshabtay/MonoAGS

The `AGSButton` class can be seen here: https://github.com/tzachshabtay/MonoAGS/blob/master/Source/Engine/AGS.Engine/ComponentsFramework/Templates/AGSButton.generated.cs

It inherits from `AGSEntity` which does have a `DoNotNotify` attribute, and can be seen here: https://github.com/tzachshabtay/MonoAGS/blob/master/Source/Engine/AGS.Engine/ComponentsFramework/AGSEntity.cs

So it shouldn't try to inject at all (and I don't want to decorate `AGSButton` with `DoNotNotify`, I have a lot of inheritors from `AGSEntity`).

**Comment by tzachshabtay** [comment]
Downgrading `Fody.PropertyChanged` to 2.1.4 works as a workaround.

**Comment by peterson1** [comment]
I'm having this same issue with version 2.2.10 as well. Downgrading to 2.2.9 fixed it for me.

**Comment by SimonCropp** [comment]
can someone upload a minimal solution that reproduces this issue. or better yet sed a PR with a failing unit test

**Comment by tmt242001** [comment]
Same issue with version 2.2.10, 2.3 and 2,4. 
Downgrading to 2.2.9 fixed it for me.

**Comment by SimonCropp** [comment]
@tmt242001 

> can someone upload a minimal solution that reproduces this issue. or better yet send a PR with a failing unit test

**Comment by tmt242001** [comment]
[PropertyChangedIssue.zip](https://github.com/Fody/PropertyChanged/files/1887888/PropertyChangedIssue.zip)

Sorry for delay reply. Try building PropertyChangedIssue project

you will get error, similar to below

Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver C:\Users\ElvinT\.nuget\packages\propertychanged.fody\2.4.0\netclassicweaver\PropertyChanged.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers()
   at InnerWeaver.Execute()
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Could not inject EventInvoker method on type 'PropertyChangedIssue.Configuration'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Either correct 'EventInvokerNames' or implement your own EventInvoker on this class. If you want to suppress this place a [DoNotNotifyAttribute] on PropertyChangedIssue.Configuration.
Type:
Fody.WeavingException
StackTrace:
   at ModuleWeaver.InjectMethod(TypeDefinition targetType, InvokerTypes& invokerType)
   at ModuleWeaver.AddOnPropertyChangedMethod(TypeDefinition targetType)
   at ModuleWeaver.FindMethodsForNodes()
   at ModuleWeaver.Execute()
   at InnerWeaver.ExecuteWeavers()
Source:
PropertyChanged.Fody
TargetSite:
Mono.Cecil.MethodDefinition InjectMethod(Mono.Cecil.TypeDefinition, InvokerTypes ByRef)
	PropertyChangedIssue		1

**Comment by tmt242001** [comment]
The issue still exist in 2.5.3

**Comment by ltrzesniewski** [comment]
@tzachshabtay please test this with v2.5.4, I'm not sure if the fix for #333 will fix your particular issue as well, as the effect is the same but the actual cause may be different (the fix is totally unrelated to `[DoNotNotify]`).

**Comment by arnemolland** [comment]
@ltrzesniewski I'm having the same issue with v2.5.4 as well.

**Comment by jantenhove** [comment]
Fody 3.03, PropertyChanged.Fody v2.5.4 gives the same eror.
`2>MSBUILD : error : Source:
2>MSBUILD : error : FodyIsolated
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Void ExecuteWeavers()
2>MSBUILD : error : Could not find 'System.Object'.
2>MSBUILD : error : Type:
2>MSBUILD : error : Fody.WeavingException
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    at TypeCache.FindType(String typeName)
2>MSBUILD : error :    at ModuleWeaver.FindCoreReferences()
2>MSBUILD : error :    at ModuleWeaver.Execute()
2>MSBUILD : error :    at InnerWeaver.ExecuteWeavers()
2>MSBUILD : error : Source:
2>MSBUILD : error : FodyHelpers
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Mono.Cecil.TypeDefinition FindType(System.String)
2>MSBUILD : error : `

**Comment by arnemolland** [comment]
@ltrzesniewski After trying to reproduce, I have found that it seems to appear in the Prism for Xamarin.Forms 'QuickStart' template. I've uploaded my solution [here](https://github.com/arnemolland/Wobb). It's pretty big, but I couldn't reproduce otherwise.

**Error message:**
`MSBUILD : error : Fody: An unhandled exception occurred: [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : Exception: [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : Failed to execute weaver /Users/arnemolland/.nuget/packages/propertychanged.fody/2.5.4/netclassicweaver/PropertyChanged.Fody.dll [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : Type: [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : System.Exception [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : StackTrace: [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error :   at InnerWeaver.ExecuteWeavers () [0x00096] in <6331e3e65b594fb399bda7ecf140a800>:0  [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error :   at InnerWeaver.Execute () [0x0004d] in <6331e3e65b594fb399bda7ecf140a800>:0  [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : Source: [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : FodyIsolated [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : TargetSite: [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : Void ExecuteWeavers() [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : Could not inject EventInvoker method on type 'Wobb.App'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Either correct 'EventInvokerNames' or implement your own EventInvoker on this class. If you want to suppress this place a [DoNotNotifyAttribute] on Wobb.App. [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : Type: [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : Fody.WeavingException [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : StackTrace: [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error :   at ModuleWeaver.InjectMethod (Mono.Cecil.TypeDefinition targetType, InvokerTypes& invokerType) [0x00026] in <20749baa9b30454992d9c45a2c8b0420>:0  [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error :   at ModuleWeaver.AddOnPropertyChangedMethod (Mono.Cecil.TypeDefinition targetType) [0x00061] in <20749baa9b30454992d9c45a2c8b0420>:0  [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error :   at ModuleWeaver.FindMethodsForNodes () [0x00026] in <20749baa9b30454992d9c45a2c8b0420>:0  [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error :   at ModuleWeaver.Execute () [0x00042] in <20749baa9b30454992d9c45a2c8b0420>:0  [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error :   at InnerWeaver.ExecuteWeavers () [0x0006b] in <6331e3e65b594fb399bda7ecf140a800>:0  [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : Source: [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : PropertyChanged.Fody [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : TargetSite: [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error : Mono.Cecil.MethodDefinition InjectMethod(Mono.Cecil.TypeDefinition, InvokerTypes ByRef) [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
MSBUILD : error :  [/Users/arnemolland/Projects/Wobb/Wobb/src/Wobb/Wobb.csproj]
    Fody:   Finished Fody 559ms.
`

**My fody.xml:**

`<?xml version="1.0" encoding="utf-8"?>
<Weavers>
    <PropertyChanged EventInvokerNames="RaisePropertyChanged"/>
</Weavers>`

**Comment by SimonCropp** [comment]
@arnemolland your repro gives a 404. can u raise a new issue

**Comment by powerdude** [comment]
I get this error when I have an object that inherits from ReactiveObject from the ReactiveUI library.  I had to create the following class and use it instead:

 `public class MyReactiveObject : ReactiveObject
    {
       protected void RaisePropertyChanged(PropertyChangedEventArgs args)
        {
            ((IReactiveObject)this).RaisePropertyChanged( args);
        }
    }`

**Comment by ltrzesniewski** [comment]
@powerdude this should have been fixed in #336. Are you sure you're using the latest version?

**Comment by powerdude** [comment]
Oops, sorry, i was indeed on an older version.  But i just upgraded and now get errors in a xamarin project when i have my own custom control.

```
1>  Fody: Fody (version 3.0.3.0) Executing
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Failed to execute weaver C:\Users\admin\.nuget\packages\propertychanged.fody\2.5.6\netclassicweaver\PropertyChanged.Fody.dll
1>MSBUILD : error : Type:
1>MSBUILD : error : System.Exception
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers()
1>MSBUILD : error :    at InnerWeaver.Execute()
1>MSBUILD : error : Source:
1>MSBUILD : error : FodyIsolated
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void ExecuteWeavers()
1>MSBUILD : error : Could not inject EventInvoker method on type 'Xamarin.Plugins.UnobtrusiveFluentValidation.ValidatableEntryControl'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Either correct 'EventInvokerNames' or implement your own EventInvoker on this class. If you want to suppress this place a [DoNotNotifyAttribute] on Xamarin.Plugins.UnobtrusiveFluentValidation.ValidatableEntryControl.
1>MSBUILD : error : Type:
1>MSBUILD : error : Fody.WeavingException
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at ModuleWeaver.InjectMethod(TypeDefinition targetType, InvokerTypes& invokerType)
1>MSBUILD : error :    at ModuleWeaver.AddOnPropertyChangedMethod(TypeDefinition targetType)
1>MSBUILD : error :    at ModuleWeaver.FindMethodsForNodes()
1>MSBUILD : error :    at ModuleWeaver.Execute()
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers()
1>MSBUILD : error : Source:
1>MSBUILD : error : PropertyChanged.Fody
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Mono.Cecil.MethodDefinition InjectMethod(Mono.Cecil.TypeDefinition, InvokerTypes ByRef)
1>MSBUILD : error :
1>  Fody:   Finished Fody 912ms.
```

**Comment by ltrzesniewski** [comment]
@powerdude check #338 for a similar issue (this should work, see if you have configured the weaver properly and that you have an accessible event invoker method like the error message suggests).

**Comment by powerdude** [comment]
@ltrzesniewski that issue helped solve my problem.
