### ISSUE TITLE
Option to call events after everything is done

### ISSUE THREAD

**Issue by Logerfo** [Fody/PropertyChanged#342]
Considering the following class:
```c#
public int a {get; set;}
private int _b;
public int b
{
   get => _b;
   set => _b = a = value;
}
```
I believe it would look like this after weaving:
```c#
var b1 = b;
var a1 = = a;
int av;
a = av = value;
OnPropertyChanged(nameof(a), a1, a);
_b = av;
OnPropertyChanged(nameof(b), b1, b);
```
I propose an option to make it look like this:
```c#
var b1 = b;
var a1 = = a;
int av;
a = av = value;
_b = av;
OnPropertyChanged(nameof(a), a1, a);
OnPropertyChanged(nameof(b), b1, b);
```
The sorting of the event calls is important. First, the properties changed in the setter body. Then, the properties which depends on the property value (getter). At last, the property itself.

Is this achievable? Thanks.

**Comment by SimonCropp** [comment]
unfortunately this is difficult to achieve. the reason for the "notify after set" is because people can put branching logic in a set. so to ensure we only notify for the props that have change, the notify is injected immediately after the set. so the notify will exist inside an branching logic and only get fired when the pro really changes.

to implement you proposal a local bool variable would need to be created for all the props changes in a set, then set those bools immediately after each changed value. then at the end of the set you need to check each bool and fire the notify.

Happy to consider a pull request that achieves this. but it is non trivial
