### ISSUE TITLE
PropertyChanged.Fody + MvvmCross 6.2 = crash

### ISSUE THREAD

**Issue by borbmizzet** [Fody/PropertyChanged#345]
Combining PropertyChanged.Fody with MvvmCross 6.2-beta results in crashing with `System.InvalidProgramException: Invalid IL code in MyApp.Core.ViewModels.LoginViewModel:set_RememberMe (bool): IL_0020: ret`

see: https://github.com/MvvmCross/MvvmCross/issues/3016
Probable Solution:  Properly handle Task-returning as well as void-returning `RaisePropertyChanged()`.

**Comment by SimonCropp** [comment]
@borbmizzet yep looks like a bug. happy to accept a PR that fixes this

**Comment by borbmizzet** [comment]
@SimonCropp Unfortunately I have no idea where to even begin with this.  I have close to zero experience with reflection, and none at all with .NET IL codes.

**Comment by SimonCropp** [comment]
start by adding your scenario to https://github.com/Fody/PropertyChanged/tree/master/TestAssemblies/AssemblyToProcess eg similar to https://github.com/Fody/PropertyChanged/tree/master/TestAssemblies/AssemblyToProcess/ClassWithIndirectImplementation.cs

and then add your expected outcome to a test eg https://github.com/Fody/PropertyChanged/blob/master/Tests/AssemblyToProcessTests.cs#L70

you should then be able to debug the test and step through the code to derive the next step. i suspect it will require a change in here https://github.com/Fody/PropertyChanged/blob/master/PropertyChanged.Fody/OnChangedWalker.cs

**Comment by borbmizzet** [comment]
Thanks.  I'll do that.

**Comment by ltrzesniewski** [comment]
I'd say you need to modify [this method](https://github.com/Fody/PropertyChanged/blob/00141e5edbed92827149b61e9aa280722d4f7454/PropertyChanged.Fody/PropertyWeaver.cs#L303-L315) so it returns `IEnumerable<Instruction>` instead of `Instruction` (fix the call sites, obviously), and if the method returns something other than `System.Void`, then just add a `pop` instruction after the `callvirt`.

This would simply ignore any return value (even if not a `Task`), which I think is the right behavior.

**Comment by borbmizzet** [comment]
@ltrzesniewski That worked perfectly.  Thanks!
