### ISSUE TITLE
Bug: custom property changed handler blocks automated invocation.

### ISSUE THREAD

**Issue by Klaus-fischer** [Fody/PropertyChanged#349]
To reproducing:
Add a class, implementing _INotifyPropertyChanged_ interface.
Self assign a Handler with the name _OnPropertyChanged_ to the _PropertyChanged_ event.

Every changed property within this class will execute the method _OnPropertyChanged_ but it will not raise the _PropertyChanged_ event.

    namespace Datatypes
    {
        using System;
        using System.Collections.Generic;
        using System.ComponentModel;
        using System.Diagnostics;
        using System.Linq;
        using PropertyChanged;

        /// <summary>
        /// Generic type to enable indention of data grid items.
        /// </summary>
        public class DataGridTreeItem : INotifyPropertyChanged
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="DataGridTreeItem"/> class.
            /// </summary>
            public DataGridTreeItem()
            {
                this.PropertyChanged += this.OnPropertyChanged;
            }

            /// <inheritdoc/>
            public event PropertyChangedEventHandler PropertyChanged;

            private void OnPropertyChanged(object sender, PropertyChangedEventArgs e)
            {
                Debug.WriteLine($"{e.PropertyName}");
            }
        }
    }

The solution that works for me was: renaming the method to _OnPropertyChangedHandler_ and everyting works as expected.

**Comment by ltrzesniewski** [comment]
That's expected behavior. When you provide an event invoker method, PropertyChanged.Fody will simply call it. Your method should then invoke the event, or do whatever it wants.

Here are the default event invoker names:

https://github.com/Fody/PropertyChanged/blob/8bc66e80622612fcb5c1e26c56d397268d62c147/PropertyChanged.Fody/EventInvokerNameResolver.cs#L10-L16

You can change these names [in the configuration](https://github.com/Fody/PropertyChanged/wiki/EventInvokerSelectionInjection).

Here are the supported signatures:
 - `(string propertyName, T before, T after)`
 - `(string propertyName, object before, object after)`
 - `(object sender, PropertyChangedEventArgs eventArgs)`
 - `(PropertyChangedEventArgs eventArgs)`
 - `(string propertyName)`

(in that order of preference)

If you don't provide any such method, PropertyChanged.Fody will provide one for you (and it will simply raise the event) - that's what happened when you renamed your method.

**Comment by SimonCropp** [comment]
Yes @ltrzesniewski is correct, this is how it is meant to work
