### ISSUE TITLE
A boolean variable named "IsChanged" defaulted as true instead of default as false

### ISSUE THREAD

**Issue by liamomg** [Fody/PropertyChanged#429]
## Preamble
Where relevant, ensure you are using the current stable versions of the following:

 * Fody version 5.1.1
 * No Fody weavers being used
 * MSBuild 16. 
 * .NET framework 4.6

#### Describe the issue

Not sure if anyone has experienced this issue. I have a boolean property which names "IsChanged" in my class. The default value of this property is true instead of false. 

#### Minimal Repro

1. Create a class (ClassA) with a boolean property and name it as "IsChanged".

> public class ClassA : INotifyPropertyChanged
>     {
>         public event PropertyChangedEventHandler PropertyChanged;
>         public bool IsChanged { get; set; }
>     }

2. In another MainClass, create an object of ClassA
3. Debug the project and have a look the object. You will see the boolean property as true.

**Comment by SimonCropp** [comment]
Please read the issue template

**Comment by liamomg** [comment]
> Please read the issue template

Hi Simon, issue upated.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by safoster88** [comment]
Just curious, these actual problems people report, are they ignored if they are not patrons?

Because this makes the idea of becoming a patron less enticing since I know most common public issues are being ignored/not fixed.

Thanks for all the hard work.

**Comment by SimonCropp** [comment]
@safoster88 this is was closed due to the fact to a few

### didnt read the issue template

the initial issue full content was 

> Not sure if anyone has experienced this issue. I have a boolean property which names "IsChanged" in my class. The default value of this property is true instead of false.

maintainer should not have to got back and forth multiple times just to tease out the information that is clearly requested in the issue template.

### Not usable repro shared

https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#minimal-repro

>  Upload this repro as part of the issue, preferably a public GitHub repository or a downloadable zip.

Too many issues are raised with "follow these x steps to reproduce". The maintainers follow those steps and cant repro. And often when the person raising the issue attempts to produce the repro they discover a bug in their own code. Essentially to verify an issue a maintainer need to have a that repro. forcing the maintainers to put the effort into re-creating that repro for every incoming issue does not scale.

### made no effort to fix the bug

https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#make-an-effort-to-fix-the-bug

### chose to ignore the comments about being a patron

Ignore the first part of the issue template about being a patron, and also ignored the issue comment


as for 

>  most common public issues are being ignored/not fixed.

legitimate and verifiable issues that are likely to have significant impact on a number of consumers are addressed, even if the person raising it is not a patron. note that a large portion of issues raised are not legit bugs. eg one of the most common ones is people using an out of date version of Fody, even though the readme for every fody weaver and the issue template explicitly calls out this issue.

maintainers simply dont have capacity to address every issue. The ones where people dont put effort into and dont look like real and/or significant issues are the most likely to get closed.

TBH in this context the "you are not a patron thing" is an more convenient way to handle them. although i have noticed a high correlation between people who ignore the patron thing and also put little effort into the issue

**Comment by SimonCropp** [comment]
@safoster88 how do you handle the above scenario in the projects you help maintain?

**Comment by safoster88** [comment]
That makes sense.

Thanks for explaining and again, thank you all for your hard work.

**Comment by safoster88** [comment]
I'm relatively new to the open source scene and don't actively contribute
to projects.

So I'm not knowledgeable in how these projects are actively maintained or
how issues are handled.

At a quick glance it looks like people reporting issues have them closed
with the main reason being they're not a patron. In my eyes, issues are bug
reports essentially, and a bug report shouldn't be ignored (but it should
adhere to template guidelines, repro project etc. to make it easier) based
on if the customer is paying or not.

But I understand and appreciate your perspective (which I didn't before I
asked).

**Comment by SimonCropp** [comment]
> issues are bug reports essentially, and a bug report shouldn't be ignored (but it should
adhere to template guidelines, repro project etc. to make it easier) based
on if the customer is paying or not.

ideally this would be true. but there are not enough people willing to work for free to enable this.

given the scenario where a person who has raised an issue, does not put adequate effort into the issue, and also does not feel inclined put any effort into fixing it themselves. who should spend their personal time verify and fix said issue?

**Comment by safoster88** [comment]
I am specifically referring to the scenario where the reporter does everything right, except for being a patron. Perhaps they don't have the ability, skill or time to fix it themselves.

If this bug is real, the issue gets closed and the potential bug is effectively ignored. Even if it's not fixed by you guys because you don't have the time to fix them all etc, doesn't it make sense to keep a log of legitimate reported issues that are actual real bugs documented so that people know about them?

This way, other people who do have the time to fix these potential issues that exist could see issues that are open and problematic. Allowing them to potentially make a pull request with a fix.

You could still prioritize (or only fix, if that way inclined) bugs reported by patrons.

**Comment by SimonCropp** [comment]
> I am specifically referring to the scenario where the reporter does everything right, except for being a patron.

if you can point me to issues that are clearly verifiable from the current description then i am happy to revisit them. But until an issue is verified IMO it is not certain it is a real bug.

As for closing stale issue if no one looks at them. many projects are starting to use stalebot
https://github.com/probot/stale#is-closing-stale-issues-really-a-good-idea
