### ISSUE TITLE
Add On<PropertyName>Changed method with Attribute

### ISSUE THREAD

**Issue by bezzad** [Fody/PropertyChanged#502]
I'm using this awesome weaver to aspect my codes. But now I have many boilerplate codes created because of the `PropertyChanged` library. My class has many properties that need their own `On<PropertyName>Changed` method to be aware of changes and referrals to higher classes.
May to create an Attribute like `AddOwnPropertyChangedAttribute` to weaving that `On<PropertyName>Changed` method in compile time?

For example use below codes:

```csharp
public class TestClass : INotifyPropertyChanged
{
     [AddOwnPropertyChanged]
     public string FamilyName { get; set; }
}
```
What gets compiled:

```csharp
public class TestClass : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;
    public event PropertyChangedEventHandler FamilyNameChanged;

    string familyName;
    public string FamilyName
    {
        get => familyName;
        set 
        {
            if (value != familyName)
            {
                familyName = value;
                OnPropertyChanged(InternalEventArgsCache.FamilyName);
                OnFamilyNameChanged();
            }
        }
    }

    public void OnPropertyChanged(string propertyName) { }

    public void OnFamilyNameChanged()  
    { 
         FamilyNameChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(FamilyName)));
    }
}
```

**Comment by ltrzesniewski** [comment]
The problem with this approach is that it wouldn't be convenient to use:

- You wouldn't be able to use `FamilyNameChanged` in the same project, because it won't exist when you compile it.
- You wouldn't even be able to easily use `FamilyNameChanged` in the same solution, because IntelliSense wouldn't know about it.

You'd need to distribute your project as a binary in order for this to be useful.

Really, this is the role of the `PropertyChanged` event, use that one, the property name is inside.

**Comment by bezzad** [comment]
You right. I didn't think about that. Thanks for the reply.
