### ISSUE TITLE
Failed Build Issue with Caliburn.Micro 2.0 RTM

### ISSUE THREAD

**Issue by mahara** [Fody/PropertyChanged#81]
The detail as I reported it here: https://github.com/Caliburn-Micro/Caliburn.Micro/issues/26#issuecomment-44557561.

This is repro-ed by installing Caliburn.Micro, Fody, and PropertyChanged.Fody NuGet packages in a WPF application (using .NET Framework 4.5.2).

Given the following code:

```
public class Model : PropertyChangedBase
{
}
```

VS2013 Update 2 build will throw the following errors:
- The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- The type 'System.ComponentModel.INotifyPropertyChanged' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ObjectModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by arisliang** [comment]
I added the two DLLs from C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades, which seem to work when build from teamcity. VS2013 doesn't appear to have this issue. It is CM 2.0.2 that I'm working with.

**Comment by drowhunter** [comment]
this problem was driving me nuts and i spent hours analysing it.

turns out i was only having the issue with 4.5.2  all other frameworks worked perfectly.

then i stumbled across this.

https://support.microsoft.com/en-us/kb/2971005

turns out microsoft put out a faulty 4.5.2  targeting pack. and you should redownload it.
