### ISSUE TITLE
It doesn't work for static properties

### ISSUE THREAD

**Issue by arteny** [Fody/PropertyChanged#85]
Even it is supported by .NET 4.5 (http://msdn.microsoft.com/en-us/library/bb613588%28v=vs.110%29.aspx#static_properties), it doesn't work with this library.
Could you implement this?

**Comment by corylulu** [comment]
@SimonCropp Can you point me to generally what files would need changing to add this? I don't mind coding it, but having a general understanding of where to start would be helpful.

**Comment by SimonCropp** [comment]
@corylulu what equivalent c# would you expect to be created?

**Comment by corylulu** [comment]
Base on the [guidelines](https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/whats-new#static_properties)

Something like: 
```
    [ImplementStaticPropertyChanged]
    public class Example
    {
        public static string Property1 { get; set; }
    }
```

To generate:
```
    public class Example
    {
        private static string _property1;

        public static string Property1
        {
            get => _property1;
            set
            {
                if (value != _property1)
                {
                    _property1 = value;
                    OnStaticPropertyChanged("Property1");
                }
            }
        }

        public static event PropertyChangedEventHandler StaticPropertyChanged;

        public static void OnStaticPropertyChanged(string propertyName, object oldValue, object newValue)
        {
            StaticPropertyChanged?.Invoke(null, new PropertyChangedEventArgs(propertyName));
        }
    }
```

**Comment by SimonCropp** [comment]
ok. the best approach is to add a new unit test that represents that scenario, it will fail since the current code base guards against it, but you can gradual change those guards to make it work and, using the unit test as a entry point, you can debug through the logic to understand how it works.

**Comment by SimonCropp** [comment]
If anyone wants to submit a PR to add static property support, i will gladly accept.  until then i am closing this

**Comment by corylulu** [comment]
Yeah, if I get time soon, I'll take a whack at it, but it's a learning curve for me since I've only made 1 fody extension before to add in attributes on certain types of properties, which was pretty easy, but still took me many hours. 

Overcoming the guards seems like a tough task tho, being unfamiliar with the code. Is there a way for me to easily bypass the guards your speaking of for initial testing? Also, can you point to the main files I'll probably need to make changes to? I'll eventually figure that stuff out, but if you know off hand, would save me some time.
