### ISSUE TITLE
Reference to "Microsoft.NETFramework.ReferenceAssemblies.net40" bubbling up

### ISSUE THREAD

**Issue by dittodhole** [Fody/PropertyChanged#902]
Hi there,

VS shows "Microsoft.NETFramework.ReferenceAssemblies.net40" being added to a net462 project with the latest release:
![image](https://user-images.githubusercontent.com/429216/195821126-c40b7366-2c76-4da9-ad40-b0a7921d0517.png)

Reason is that the [package reference](https://github.com/Fody/PropertyChanged/blob/master/PropertyChanged/PropertyChanged.csproj#L24) is not  defined as private:
```xml
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net40" Version="1.0.2" />
```

[nuget.org](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies.net40) provides following snippet (also for 1.0.2):
```xml
<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net40" Version="1.0.3">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
```

Was the reference just manually added, or is there a reason behind making the dependency transient?
If not, could you possible revert to a private one?

And, could you possibly update the reference to 1.0.3?

Best
Andreas

**Comment by ltrzesniewski** [comment]
Oops. Thanks for noticing this.

To be honest I don't understand why this package has been added. @tom-englert can you comment on this please?

**Comment by tom-englert** [comment]
It did not compile on my machine, saying `error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found`. 
I copied it from here: https://github.com/jbevain/cecil/blob/e052ab52e44fd2a6564964e47e79929068731916/Directory.Build.props#L16-L18, rather should have used the official nuget snippet.

**Comment by ltrzesniewski** [comment]
That's strange, I tried to build it on my WSL without the reference, and it worked just fine. I think the SDK is supposed to add the necessary reference assemblies.

**Comment by ltrzesniewski** [comment]
On a *totally* unrelated note:

- Don't you prefer to merge PRs instead of rebasing them? GitHub then adds a merge commit which references the PR id, which lets you find additional info such as the comments in the PR. I'd only keep rebasing dependabot PRs.
- Can we comment out the beep please? It's very unpleasant each time one opens the solution. ^^

**Comment by tom-englert** [comment]
I have one machine where it doesn't work without, but only within VS, MSBuild works fine. Got no clue where the root cause is. 

Also having net40 as the first entry in the `<TargetFrameworkds>` results in this fancy behavior, where VS is playing with itself:
(I don't click anything, and this will run forever)
![devenv_eCS6qB9tzw](https://user-images.githubusercontent.com/10229954/195983308-cbd3f462-d50a-4427-a816-f335e3165b46.gif)

**Comment by tom-englert** [comment]
Usually I prefer a flat history without the cluttered graph generated by merge, which is more confusing than helpful. (https://www.tugberkugurlu.com/archive/resistance-against-london-tube-map-commit-history-a-k-a--git-merge-hell)

Anyhow, thanks to dependabot the history of all Fody repos is rendered totally useless, so using merge instead of rebase would not make it worse.
